name: Verify CSharp Unit Tests

on:
  pull_request:
    paths:
      - "csharp/**"

defaults:
  run:
    working-directory: ./csharp

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - name: 🍗 Restore nuget
        run: dotnet restore && dotnet build
      - name: Test with dotnet
        run: |
          dotnet test --no-restore -c Release